export enum ArticleCategory {
    GENERAL_ANNOUNCEMENTS = 'GENERAL_ANNOUNCEMENTS',
    EVENTS = 'EVENTS',
    CONSTRUCTION_AND_TRAFFIC = 'CONSTRUCTION_AND_TRAFFIC',
    CITIZEN_PARTICIPATION = 'CITIZEN_PARTICIPATION',
    PUBLIC_SAFETY = 'PUBLIC_SAFETY',
    EDUCATION_AND_CULTURE = 'EDUCATION_AND_CULTURE',
    ENVIRONMENT_AND_SUSTAINABILITY = 'ENVIRONMENT_AND_SUSTAINABILITY',
    SOCIAL_AND_HEALTH = 'SOCIAL_AND_HEALTH',
    ECONOMY_AND_BUSINESS = 'ECONOMY_AND_BUSINESS',
    LEISURE_AND_SPORTS = 'LEISURE_AND_SPORTS',
  }